# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ProcessCompose < Formula
  desc ""
  homepage "https://github.com/F1bonacc1/process-compose"
  version "0.43.2"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/F1bonacc1/process-compose/releases/download/v0.43.2/process-compose_0.43.2_Darwin_arm64.tar.gz"
      sha256 "0b0dea229e83a454cd212e6500891e4ca15b0c38541f26c95cb6694e3846cdff"

      def install
        bin.install "process-compose"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/F1bonacc1/process-compose/releases/download/v0.43.2/process-compose_0.43.2_Darwin_x86_64.tar.gz"
      sha256 "153576673715741c676ce2349601c378f1bc72b9e937383fd1293930482f2713"

      def install
        bin.install "process-compose"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/F1bonacc1/process-compose/releases/download/v0.43.2/process-compose_0.43.2_Linux_armv6.tar.gz"
      sha256 "d0b4afd5b01c65a30ae1f30efcb38dd27a81b0a67d66fa15a0be6d04dce2f2ce"

      def install
        bin.install "process-compose"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/F1bonacc1/process-compose/releases/download/v0.43.2/process-compose_0.43.2_Linux_arm64.tar.gz"
      sha256 "057e9e9720adbe706ccb44ce049994cbcac4ee4917344c1facd399acfd042a0a"

      def install
        bin.install "process-compose"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/F1bonacc1/process-compose/releases/download/v0.43.2/process-compose_0.43.2_Linux_x86_64.tar.gz"
      sha256 "e750231f449b2c938850123715092c8bbf150d0e4f4362abf310823b3c066b68"

      def install
        bin.install "process-compose"
      end
    end
  end
end
